cppcheck

diff --git a/.github/workflows/build-win.yml b/.github/workflows/build-win.yml
--- a/.github/workflows/build-win.yml
+++ b/.github/workflows/build-win.yml
@@ -21,13 +21,13 @@ jobs:
 
     - name: cppcheck-install
       run: |
-        choco install cppcheck --confirm
-        exePath="C:/Program Files/Cppcheck/cppcheck.exe"
-        if [[ -f "$exePath" ]]; then
-            exit 0
-        else
-            echo "Couldn't find CppCheck exe file"
-            exit 1
+        choco install cppcheck --confirm || EXIT_CODE=$?
+        if [[ $EXIT_CODE -eq 3010 ]]; then
+          echo "Installation signaled reboot (exit code 3010), ignoring..."
+          exit 0
+        elif [[ $EXIT_CODE -ne 0 ]]; then
+          echo "Installation failed with exit code $EXIT_CODE"
+          exit $EXIT_CODE
         fi
       shell: bash
 
