static code analysis (#68)

diff --git a/.github/workflows/build-win.yml b/.github/workflows/build-win.yml
--- a/.github/workflows/build-win.yml
+++ b/.github/workflows/build-win.yml
@@ -15,103 +15,80 @@ jobs:
     runs-on: windows-2022
     steps:
     - uses: actions/checkout@v2
+
     - name: git-update-dependecies
-      run: git submodule update --init --recursive | Write-Host
+      run: git submodule update --init --recursive
+      shell: bash
+
     - name: gen
-      shell: pwsh
       run: |
-          Start-Process -FilePath "win-gen.bat" " > GenLog.txt" -Wait -NoNewWindow -PassThru 
-          cat GenLog.txt
-          if (Select-String -Path GenLog.txt -Pattern "Configuring incomplete" -SimpleMatch -Quiet)
-          {
+        sh win-gen.bat > GenLog.txt -Wait -NoNewWindow -PassThru 
+        cat GenLog.txt
+        if (grep -Fxq "$GenLog.txt" "Configuring incomplete")
+        then
             exit 1
-          }
-          exit 0
+        fi
+        exit 0
+      shell: bash
+
+    - name: cppcheck-run
+      run: |
+        sh win-cppcheck.bat > CppCheckLog.txt -Wait -NoNewWindow -PassThru
+        cat CppCheckLog.txt
+        if (grep -Fxq "$CppCheckLog.txt" "cppcheck fail:")
+        then
+          echo "CppCheck fail"
+          exit 1
+        fi
+        exit 0
+      shell: bash
+
     - name: build-win
-      shell: pwsh
       run: |
-          Start-Process -FilePath "win-build.bat" " > BuildLog.txt" -Wait -NoNewWindow -PassThru
-          cat BuildLog.txt
-          if (Select-String -Path BuildLog.txt -Pattern "inworld-ndk.vcxproj ->" -SimpleMatch -Quiet)
-          {
-            "inworld-ndk built successfully"
-          }
-          else
-          {
-            exit 1
-          }
-          if (Select-String -Path BuildLog.txt -Pattern "inworld-ndk-app.vcxproj ->" -SimpleMatch -Quiet)
-          {
-            "inworld-ndk-app built successfully"
-          }
-          else
-          {
-            exit 1
-          }
-          if (Select-String -Path BuildLog.txt -Pattern "inworld-ndk-unit.vcxproj ->" -SimpleMatch -Quiet)
-          {
-            "inworld-ndk-unit built successfully"
-          }
-          else
-          {
-            exit 1
-          }
-          if (Select-String -Path BuildLog.txt -Pattern "[  FAILED  ]" -SimpleMatch -Quiet)
-          {
-            exit 1
-          }
-          exit 0
+        sh win-build.bat > BuildLog.txt -Wait -NoNewWindow -PassThru
+        cat BuildLog.txt
+        if (grep -Fxq "$BuildLog.txt" ": error")
+        then
+          exit 1
+        fi
+        if (grep -Fxq "$BuildLog.txt" "FAILED")
+        then
+          exit 1
+        fi
+        exit 0
+      shell: bash
+
     - name: clear-cmake-cache
-      shell: pwsh
-      run: |
-          Remove-Item -Path "build\CMakeCache.txt"
+      run: rm -f build/CMakeCache.txt
+      shell: bash
+
     - name: gen-shared
-      shell: pwsh
       run: |
-          Start-Process -FilePath "win-gen-shared.bat" " > GenLog.txt" -Wait -NoNewWindow -PassThru 
-          cat GenLog.txt
-          if (Select-String -Path GenLog.txt -Pattern "Configuring incomplete" -SimpleMatch -Quiet)
-          {
+        sh win-gen-shared.bat > GenLog.txt -Wait -NoNewWindow -PassThru
+        cat GenLog.txt
+        if grep -Fxq "$GenLog.txt" "Configuring incomplete"
+        then
             exit 1
-          }
-          exit 0
+        fi
+        exit 0
+      shell: bash
+
     - name: build-win-shared
-      shell: pwsh
       run: |
-          Start-Process -FilePath "win-build.bat" " > BuildLog.txt" -Wait -NoNewWindow -PassThru
-          cat BuildLog.txt
-          if (Select-String -Path BuildLog.txt -Pattern "inworld-ndk.vcxproj ->" -SimpleMatch -Quiet)
-          {
-            "inworld-ndk built successfully"
-          }
-          else
-          {
-            exit 1
-          }
-          if (Select-String -Path BuildLog.txt -Pattern "inworld-ndk-app.vcxproj ->" -SimpleMatch -Quiet)
-          {
-            "inworld-ndk-app built successfully"
-          }
-          else
-          {
-            exit 1
-          }
-          if (Select-String -Path BuildLog.txt -Pattern "inworld-ndk-unit.vcxproj ->" -SimpleMatch -Quiet)
-          {
-            "inworld-ndk-unit built successfully"
-          }
-          else
-          {
-            exit 1
-          }
-          if (Select-String -Path BuildLog.txt -Pattern "[  FAILED  ]" -SimpleMatch -Quiet)
-          {
-            exit 1
-          }
-          exit 0
-    - uses: actions/cache/save@v3
+        sh win-build.bat > BuildLog.txt -Wait -NoNewWindow -PassThru
+        cat BuildLog.txt
+        if (grep -Fxq "$BuildLog.txt" ": error")
+        then
+          exit 1
+        fi
+        if (grep -Fxq "$BuildLog.txt" "FAILED")
+        then
+          exit 1
+        fi
+        exit 0
+      shell: bash
+
+    - uses: actions/cache@v3
       with:
         path: build\Package
         key: ndk-cache-win64-${{ github.sha }}
-
-         
