use installed cppcheck (#69)

diff --git a/.github/workflows/build-win.yml b/.github/workflows/build-win.yml
--- a/.github/workflows/build-win.yml
+++ b/.github/workflows/build-win.yml
@@ -16,6 +16,13 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
+    - name: cppcheck-install
+      run: |
+          choco install cppcheck
+          echo "Ignore this error. Chocolately returns non-zero code on successful Cppcheck install."
+      shell: pwsh
+      continue-on-error: true
+
     - name: git-update-dependecies
       run: git submodule update --init --recursive
       shell: bash
@@ -24,8 +31,7 @@ jobs:
       run: |
         sh win-gen.bat > GenLog.txt -Wait -NoNewWindow -PassThru 
         cat GenLog.txt
-        if (grep -Fxq "$GenLog.txt" "Configuring incomplete")
-        then
+        if grep -Fq "$GenLog.txt" "Configuring incomplete"; then
             exit 1
         fi
         exit 0
@@ -35,10 +41,9 @@ jobs:
       run: |
         sh win-cppcheck.bat > CppCheckLog.txt -Wait -NoNewWindow -PassThru
         cat CppCheckLog.txt
-        if (grep -Fxq "$CppCheckLog.txt" "cppcheck fail:")
-        then
-          echo "CppCheck fail"
-          exit 1
+        if grep -Fq "cppcheck fail:" CppCheckLog.txt; then
+            echo "CppCheck fail"
+            exit 1
         fi
         exit 0
       shell: bash
@@ -47,12 +52,10 @@ jobs:
       run: |
         sh win-build.bat > BuildLog.txt -Wait -NoNewWindow -PassThru
         cat BuildLog.txt
-        if (grep -Fxq "$BuildLog.txt" ": error")
-        then
+        if grep -Fq "$BuildLog.txt" ": error"; then
           exit 1
         fi
-        if (grep -Fxq "$BuildLog.txt" "FAILED")
-        then
+        if grep -Fq "$BuildLog.txt" "FAILED"; then
           exit 1
         fi
         exit 0
@@ -66,8 +69,7 @@ jobs:
       run: |
         sh win-gen-shared.bat > GenLog.txt -Wait -NoNewWindow -PassThru
         cat GenLog.txt
-        if grep -Fxq "$GenLog.txt" "Configuring incomplete"
-        then
+        if grep -Fq "$GenLog.txt" "Configuring incomplete"; then
             exit 1
         fi
         exit 0
@@ -77,12 +79,10 @@ jobs:
       run: |
         sh win-build.bat > BuildLog.txt -Wait -NoNewWindow -PassThru
         cat BuildLog.txt
-        if (grep -Fxq "$BuildLog.txt" ": error")
-        then
+        if grep -Fq "$BuildLog.txt" ": error"; then
           exit 1
         fi
-        if (grep -Fxq "$BuildLog.txt" "FAILED")
-        then
+        if grep -Fq "$BuildLog.txt" "FAILED"; then
           exit 1
         fi
         exit 0
